services:
  - type: web
    name: plan-date
    runtime: docker
    plan: free
    repo: https://github.com/monis2512/invitation
    branch: main
    healthCheckPath: /api/health

    envVars:
      - key: DB_HOST
        fromDatabase:
          name: plan-date-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: plan-date-db
          property: port

      - key: DB_NAME
        fromDatabase:
          name: plan-date-db
          property: database

      - key: DB_USER
        fromDatabase:
          name: plan-date-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: plan-date-db
          property: password

      - key: ADMIN_USERNAME
        sync: false

      - key: ADMIN_PASSWORD
        sync: false

      - key: COOKIE_SECURE
        value: "true"

      - key: COOKIE_SAME_SITE
        value: "lax"

databases:
  - name: plan-date-db
    plan: free
